// src/sites.js
// Tourist sites on Pushkinskaya Street, Rostov-on-Don.
// Per the assignment: historical buildings and monuments only — NO military buildings.
// Coordinates are real and used for GPS-assisted identification.
// Each site carries both Russian and English text so the UI can switch languages.

const SITES = [
  {
    id: 'pushkin-monument',
    name: 'Памятник А. С. Пушкину',
    nameEn: 'Monument to Alexander Pushkin',
    type: 'monument',
    address: 'Пушкинская ул. / Ворошиловский пр.',
    addressEn: 'Pushkinskaya St. / Voroshilovsky Ave.',
    lat: 47.222870,
    lng: 39.720320,
    year: '1959',
    authors: 'Скульптор Г. А. Шульц, архитектор М. А. Минкус',
    authorsEn: 'Sculptor G. A. Schultz, architect M. A. Minkus',
    text: 'Памятник установлен в 1959 году на пересечении Пушкинской улицы и Ворошиловского проспекта. Авторы — скульптор Г. А. Шульц и архитектор М. А. Минкус. Это первый памятник в Ростове-на-Дону, посвящённый литературной тематике. Объект культурного наследия регионального значения. Позднее площадь вокруг монумента украсили фонарями, стилизованными под XIX век.',
    textEn: 'The monument was erected in 1959 at the intersection of Pushkinskaya Street and Voroshilovsky Avenue. It was created by sculptor G. A. Schultz and architect M. A. Minkus. It is the first monument in Rostov-on-Don dedicated to a literary theme, and a regional cultural heritage site. The surrounding square was later decorated with lanterns styled after the 19th century.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'paramonov-mansion',
    name: 'Особняк Н. Е. Парамонова',
    nameEn: 'Paramonov Mansion (Zhdanov Scientific Library)',
    type: 'building',
    address: 'Пушкинская ул., 148',
    addressEn: '148 Pushkinskaya St.',
    lat: 47.226936,
    lng: 39.725434,
    year: '1914',
    authors: 'Для купца и промышленника Н. Е. Парамонова',
    authorsEn: 'Built for merchant and industrialist N. E. Paramonov',
    text: 'Изящный белый особняк с колоннадой, построенный в 1914 году для купца и промышленника Николая Парамонова в стиле неоклассицизм. Главный северный фасад имеет симметричную композицию с шестиколонным портиком ионического ордера. После национализации здание служило клубом строителей, затем станцией переливания крови, а с 1950-х годов — научной библиотекой. Сегодня здесь располагается Зональная научная библиотека ЮФУ имени Ю. А. Жданова.',
    textEn: 'An elegant white mansion with a colonnade, built in 1914 for merchant and industrialist Nikolai Paramonov in the neoclassical style. Its main northern facade has a symmetrical composition with a six-column Ionic portico. After nationalization the building served as a builders\u2019 club, then a blood-transfusion station, and from the 1950s as a scientific library. Today it houses the Zonal Scientific Library of Southern Federal University, named after Yu. A. Zhdanov.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'fine-arts-museum',
    name: 'Ростовский областной музей изобразительных искусств',
    nameEn: 'Rostov Regional Museum of Fine Arts',
    type: 'building',
    address: 'Пушкинская ул., 115',
    addressEn: '115 Pushkinskaya St.',
    lat: 47.224870,
    lng: 39.722330,
    year: '1898',
    authors: 'Архитектор Н. А. Дорошенко',
    authorsEn: 'Architect N. A. Doroshenko',
    text: 'Областной Музей изобразительных искусств расположен в старинном особняке, построенном в 1898 году по проекту архитектора Н. А. Дорошенко. Находится неподалёку от памятника А. С. Пушкину. Один из значимых художественных музеев Юга России, хранящий коллекции русского и западноевропейского искусства.',
    textEn: 'The Regional Museum of Fine Arts is housed in an old mansion built in 1898 to a design by architect N. A. Doroshenko, near the Pushkin monument. It is one of the significant art museums of southern Russia, holding collections of Russian and Western European art.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'bakulin-house',
    name: 'Жилой дом И. Т. Бакулина',
    nameEn: 'Bakulin Residential House',
    type: 'building',
    address: 'Пушкинская ул., 13',
    addressEn: '13 Pushkinskaya St.',
    lat: 47.220150,
    lng: 39.715600,
    year: 'конец XIX века',
    authors: 'Стиль эклектика',
    authorsEn: 'Eclectic style',
    text: 'Жилой дом И. Т. Бакулина построен в конце XIX века в стиле эклектика. Является памятником архитектуры. Один из характерных образцов исторической застройки начала Пушкинской улицы.',
    textEn: 'The Bakulin residential house was built in the late 19th century in the eclectic style and is a listed architectural monument. It is a characteristic example of the historical development at the start of Pushkinskaya Street.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'betani-house',
    name: 'Жилой дом В. В. Бетани',
    nameEn: 'Betani Residential House',
    type: 'building',
    address: 'Пушкинская ул., 19',
    addressEn: '19 Pushkinskaya St.',
    lat: 47.220520,
    lng: 39.716240,
    year: '1904',
    authors: 'Стиль эклектика',
    authorsEn: 'Eclectic style',
    text: 'Жилой дом В. В. Бетани построен в 1904 году в стиле эклектика. Фасад здания — часть исторического облика Пушкинской улицы с её характерной архитектурной пластикой конца XIX — начала XX веков.',
    textEn: 'The Betani residential house was built in 1904 in the eclectic style. Its facade is part of the historical character of Pushkinskaya Street, with the architectural detailing typical of the late 19th and early 20th centuries.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'pushkin-spheres',
    name: 'Памятник «Пушкинские герои» (шары)',
    nameEn: 'Pushkin Spheres Monument',
    type: 'monument',
    address: 'Пушкинский бульвар',
    addressEn: 'Pushkinsky Boulevard',
    lat: 47.223900,
    lng: 39.721800,
    year: 'современный',
    authors: 'Скульптурная группа',
    authorsEn: 'Sculptural group',
    text: 'Знаменитые «пушкинские шары» — скульптурная группа на бульваре, посвящённая героям произведений А. С. Пушкина. Одно из самых узнаваемых украшений Пушкинской улицы и популярное место для фотографий.',
    textEn: 'The famous "Pushkin spheres" are a sculptural group on the boulevard dedicated to the characters of Pushkin\u2019s works. They are one of the most recognizable features of Pushkinskaya Street and a popular spot for photos.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'squirrel-sculpture',
    name: 'Скульптура «Белка» (Сказка о царе Салтане)',
    nameEn: 'Squirrel Sculpture',
    type: 'monument',
    address: 'Пушкинская ул. / Газетный пер.',
    addressEn: 'Pushkinskaya St. / Gazetny Ln.',
    lat: 47.221500,
    lng: 39.718900,
    year: '2023',
    authors: 'Коллектив из 30 мастеров',
    authorsEn: 'A team of 30 craftspeople',
    text: 'Бронзовая скульптура белки по мотивам «Сказки о царе Салтане» А. С. Пушкина, установленная в 2023 году на пересечении Пушкинской улицы и Газетного переулка. В создании скульптуры приняли участие 30 мастеров.',
    textEn: 'A bronze squirrel sculpture inspired by Pushkin\u2019s "Tale of Tsar Saltan", installed in 2023 at the intersection of Pushkinskaya Street and Gazetny Lane. Thirty craftspeople took part in creating it.',
    colorSignature: null,
    photos: []
  },
  {
    id: 'four-lions',
    name: 'Городская скульптура «Четыре льва»',
    nameEn: 'Four Lions Sculpture',
    type: 'monument',
    address: 'Пушкинская ул. / пер. Семашко',
    addressEn: 'Pushkinskaya St. / Semashko Ln.',
    lat: 47.221900,
    lng: 39.719600,
    year: 'современный',
    authors: 'По мотивам произведений А. С. Пушкина',
    authorsEn: 'Inspired by Pushkin\u2019s works',
    text: 'Городская скульптура «Четыре льва» с персонажами по мотивам произведений Александра Сергеевича Пушкина установлена на пересечении Пушкинской улицы с переулком Семашко.',
    textEn: 'The "Four Lions" city sculpture, featuring characters inspired by the works of Alexander Pushkin, stands at the intersection of Pushkinskaya Street and Semashko Lane.',
    colorSignature: null,
    photos: []
  }
];

module.exports = { SITES };
